### ISSUE TITLE
IndexError; too many indices for array when trying to run

### ISSUE THREAD

**Issue by TWAndrews** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#1]
I'm trying to run this code and getting the error messages below:

IndexErrorTraceback (most recent call last)
<ipython-input-4-333fe30e6544> in <module>()
      4 print '> Loading data... '
      5 
----> 6 X_train, y_train, X_test, y_test = lstm.load_data('sinwave.csv', seq_len, True)
      7 
      8 print '> Data Loaded. Compiling...'

<ipython-input-2-9e89c8e00bee> in lstm.load_data(filename, seq_len, normalise_window)
     18 
     19     row = round(0.9 * result.shape[0])
---> 20     train = result[:row, :]
     21     np.random.shuffle(train)
     22     x_train = train[:, :-1]

IndexError: too many indices for array

**Comment by TWAndrews** [comment]
Looks like this is an issue with Windows vs. *nix line endings.  Addressed locally by removing the carriage return in the split on like 13

**Comment by cuiyi129** [comment]
I have encountered the same problem.Can you tell me how to deal with it.Thanks.
