### ISSUE TITLE
Normalizing? - Can't get it.

### ISSUE THREAD

**Issue by Steviey** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#11]
I read the corresponding article (completely).
http://www.jakob-aungiers.com/articles/a/LSTM-Neural-Network-for-Time-Series-Prediction

But I can't get it, what normalizing in this example does.
Could someone explain it any further?

**Comment by jaungiers** [comment]
John, GitHub issues aren't a discussion forum for your learning. They're for reporting genuine issues with the code (which does not include you being unable to figure out how to run it). Please try StackOverflow or the comments on the accompanying article.

**Comment by Steviey** [comment]
Thank you jaungiers.
Do you have a link for comments on the accompanying article?

**Comment by Steviey** [comment]
Update: Got it. My Chrome doesn't display the comments so I switched the browser.
