### ISSUE TITLE
Addition of Exogenous Variable for LSTM Time Prediction.

### ISSUE THREAD

**Issue by scorpionhiccup** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#12]
I wanted to ask if the addition of other factors than what we are predicting can be added to the model that you have created for sp500.csv file. For example, adding the book value, twitter sentiment score, etc.

**Comment by jaungiers** [comment]
Yes you certainly can add higher dimensions into LSTMs. I might do an article on that in the near future. For now feel free to experiment yourself.
