### ISSUE TITLE
Type error int32

### ISSUE THREAD

**Issue by yl2811284434** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#13]
When I runs, lstm.py appears one error in line 53(return_sequences=True). The error is that expected int32, got list containing Tensors of type '_Message' instead

**Comment by STHSF** [comment]
I think your Python env is wrong, if you run it on python 3.5, the error will disappear

**Comment by STHSF** [comment]
@yl2811284434 I think your Python env is wrong, if you run it on python 3.5, the error will disappear
