### ISSUE TITLE
Model parameter more than number of samples

### ISSUE THREAD

**Issue by mikelam14** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#18]
Hi @jaungiers , thanks for the code. 

This is a general question about training a LSTM model. When I check the model we have for sp500, there are totally 70901 parameters while we only have 3709 rows of training samples. How is overfitting not happening in this case? Or for RNN we have a different way to compare number of parameters with number of training samples? Thanks.
![image](https://cloud.githubusercontent.com/assets/11824615/26641569/02911fb6-45f9-11e7-8fac-79cc337f270b.png)

**Comment by jaungiers** [comment]
Hey, I'm not 100% sure of the question, but as for the rows of training examples, with 3709 rows you have to remember that each "row" is a sequential window of size N (N=50 in this case). Hence the number of individual training points is rows*N which if you have 3709 rows in this case puts the total at 185450.
