### ISSUE TITLE
The code can't predict 'true' test data which is not exist?

### ISSUE THREAD

**Issue by wyqnumber** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#19]
For example:
    In sp500.csv, there is 4171 data。But I want to another 500 data. 4171 + 500 = 4671.
    How do it? Thank you!

**Comment by jaungiers** [comment]
This is not a bug. To append more test data add it to your data file and split along the index, or alternatively channel it into your prediction some other way. As long as it's in the numpy array format to feed into the model it will work.
