### ISSUE TITLE
Predicting values outside the range?

### ISSUE THREAD

**Issue by donjae** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#20]
Hi, (kinda new to LSTM models)

Quick question: instead of predicting the values at every 50th data point on the test set, how would I apply the model to predict future values? Example, predicting the next data point, or next 10, 20, or X amount?

How can I apply the model.predict function for that case?

**Comment by KarimJedda** [comment]
Hi, I think it's this line:
https://github.com/jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction/blob/master/run.py#L45
