### ISSUE TITLE
Predictions always up

### ISSUE THREAD

**Issue by johnnogent** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#21]
Hello, thank you for this code
predictions are always up
I have not made any change to the code, I am running in Python 3.6 and tensorflow 1.2.1
![prediction](https://user-images.githubusercontent.com/17167735/30835638-78c8f336-a259-11e7-87bf-f2198307c510.png)

**Comment by fanis0990** [comment]
You have too many eras

**Comment by fanis0990** [comment]
You have too many eras

**Comment by pusj** [comment]
@fanis0990 

Eras? Do you mean epocs?

**Comment by fanis0990** [comment]
@pusj 
Of course

**Comment by pusj** [comment]
@fanis0990 ,

Is it possible to have too many epochs?

**Comment by xdg2016** [comment]
Hello, thank you for the code, when I ran it on the sp500.csv,I set the normalise_window=False,however the predicted result was : point_by_point_predictions: [ 8.60885715  8.60885715  8.60885715  8.60885715  8.60885715  8.60885715, ...] , I'm a green hand ,please tell me,how should I do ? I want to use the real data,and see the new results,thank you !

**Comment by c2johnny** [comment]
I am still new to the domain but I suspect the code segment inside the prediction function is the root problem:
```
for j in range(prediction_len):
  predicted.append(model.predict(curr_frame[newaxis,:,:])[0,0])
  curr_frame = curr_frame[1:]
  curr_frame = np.insert(curr_frame, [window_size-1], predicted[-1], axis=0)
  prediction_seqs.append(predicted)
```
What it does is shifting left the predicted value in the curr_frame and this will increase weight of the subsequent predictions. Thus the result is always reinforcing the initial trend. 

Another issue is the prediction data should be shifted along the x-axis to the amount of prediction length. Remember the design was using last 49 ticks to predict the 50th tick. Therefore the graph should be plotted 49 ticks after the true data.

**Comment by CaroleHe** [comment]
I encountered the same problem with all the downside trends, while the epoch was set to be 1. So why this problem occurred? Anyone has some ideas?

**Comment by chutongz** [comment]
@lodeblomme ,

Hi, I'm having the same problem that the prediction always go upwards. And I tried your way that to remove that line in lstm.py, and the problem turns to go downwards :(epoch=1)
![figure_3](https://user-images.githubusercontent.com/30098450/40895395-c1466adc-67e1-11e8-979d-fc8b65cd98c4.png)
 This is how the prediction is if I remove the data shuffle part.
![figure_4](https://user-images.githubusercontent.com/30098450/40895413-e05448c2-67e1-11e8-9df4-6afcd9733f32.png)
This is how it works if I use the shuffle part.
Could you please tell me how did you fix the problem and the epochs you set?
Any help is appreciated! Thanks!
