### ISSUE TITLE
what's the version of tensorflow and python ?

### ISSUE THREAD

**Issue by kkyimasi** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#3]
I use tensorflow version 0.18,python2.7;
raise ValueError("Cannot take the length of Shape with unknown rank.")

**Comment by jaungiers** [comment]
Python 2.7
Tensorflow 0.12.1
Keras 1.2.1
Numpy 1.11.2

**Comment by vinayakumarr** [comment]
i have separate train and test files. Could you please tell how to train and test with your code

**Comment by jaungiers** [comment]
@vinayakumarr that is something inherently simple. I am not teaching you Python 101. I suggest you learn the concepts of coding in Python first before trying machine learning. Most of these things just require a little bit of time and brain power to work out yourself.

**Comment by jaungiers** [comment]
Code has been updated to support codebase Python 3.5 rather than 2.7 now.
