### ISSUE TITLE
Normalise Function?

### ISSUE THREAD

**Issue by Meng188** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#31]
Thanks for the review！
 I don't understand the process of data processing by this program. What is the meaning of the normalise function? Is it specific to the stock data?Can it be done by other methods? What effect will it have?
Thank you very much if someone takes the time to reply to me!

**Comment by Charly-Empereur-mot** [comment]
Data are normalized within each window by the first data point. So for each dimension of the input data (= each column), within each window, the first point is always 0 and the next points of the window are the returns. This makes the data stationary within each window.
