### ISSUE TITLE
epochs set 2, train raise error 

### ISSUE THREAD

**Issue by zbsean** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#39]
generate_train_batch is already add "while True:"
but, train raise error.
ValueError: Error when checking input: expected lstm_1_input to have 3 dimensions, but got array with shape (8, 1)

**Comment by linlin994395** [comment]
@zbsean 
me too. already added but still raise error
ValueError: Error when checking input: expected lstm_1_input to have 3 dimensions, but got array with shape (8, 1)

**Comment by frapercan** [comment]
the same
