### ISSUE TITLE
Issues reproducing sine wave example

### ISSUE THREAD

**Issue by robotdude17** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#4]
I've tried to reproduce the sine wave example using the following code in the main function seen below.

Apparently, something went wrong, see the image I have received.

Do you know what I need to fix in order to reproduce your example?

Thanks!

#Main Run Thread
if __name__=='__main__':

	os.system('clear')
	global_start_time = time.time()
	epochs  = 1
	seq_len = 50

	print '> Loading data... '

	X_train, y_train, X_test, y_test = lstm.load_data('sinwave.csv', seq_len, True)

	print '> Data Loaded. Compiling...'

	model = lstm.build_model([1, 50, 100, 1])

	model.fit(
	    X_train,
	    y_train,
	    batch_size=512,
	    nb_epoch=epochs,
	    validation_split=0.05)

	predicted = lstm.predict_point_by_point(model, X_test)        

	print 'Training duration (s) : ', time.time() - global_start_time
	plot_results(predicted, y_train)

![prediction_sine_wave_01](https://cloud.githubusercontent.com/assets/26026201/23587654/6b0dac12-01b1-11e7-9a6b-83a3b60b7691.png)

**Comment by jaungiers** [comment]
For starters it seems you've got an issue loading the actual sin wave data... The true data should be a high-frequency sin wave over the time period... Not a constant of -2.0... Please review your ETL procedures and data file.

**Comment by simonholgate** [comment]
I had a similar problem. I traced it to the importing of the sin wave data which is all quoted strings (at least on OS X High Sierra and Python 3.6.3). Converting the data after reading and decoding `data = f.decode().split('\n')` with:
`data = list(map(float, data))` (which converts all the data to floats) to seems to do the trick.

**Comment by markjay4k** [comment]
@robotdude17 With ```python seq_len = 50```, and ```python normalise_window = True```, both ```y_train``` and ```y_test``` will have all entries equal to 2.

I would suggest setting ```python normalise_window = False```

basically use this line instead

```python X_train, y_train, X_test, y_test = lstm.load_data('sinwave.csv', seq_len, True)```
