### ISSUE TITLE
One more Point

### ISSUE THREAD

**Issue by Jens1985** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#51]
Hello, i want to get one more point out of the Plot.
True Data and Prediciton end at the same Time. I need prediction one Point in the future.

Like this:
![anmerkung 2018-12-30 152657](https://user-images.githubusercontent.com/46263077/50548103-64828f00-0c47-11e9-9afe-2e7796421cd1.jpg)

How must i modify the Code?

**Comment by jaungiers** [comment]
This is not a code issue. Please do not raise it as one.
