### ISSUE TITLE
ImportError: No module named 'lstm'

### ISSUE THREAD

**Issue by Ankit1543** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#8]
import lstm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'lstm'

**Comment by jaungiers** [comment]
Please get a good understanding of coding in Python before opening trivial issues.
You've either renamed the lstm.py file or moved it to separate directories from where you're running your scripts from.

**Comment by Ankit1543** [comment]
Dear Sir,
I am sorry for my blunder.I am beginner.I get confused by a tensorflow
tutorial I didn't want to let you know about that.Sir can you suggest me
book,article or tutorial that can help me.
Thank you.
