### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by wwgjob** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#86]
![image](https://user-images.githubusercontent.com/78298695/106380176-71a47600-63eb-11eb-8b4d-1b945ab867ae.png)

how can i add more columns?

**Comment by hc-berkaydin** [comment]
Go to config.json write the names of the columns, after that change your input dimensions to the number of columns
`"model": {
		"loss": "mse",
		"optimizer": "adam",
		"save_dir": "saved_models",
		"layers": [
			{
				"type": "lstm",
				"neurons": 100,
				"input_timesteps": 49,
				**"input_dim": 4,**
				"return_seq": true
			},`

**Comment by wwgjob** [comment]
thx you.
